server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/v3/api-docs
          filters:
            - StripPrefix=2

        - id: catalog-service-docs
          uri: lb://catalog-service
          predicates:
            - Path=/gateway/catalog/v3/api-docs
          filters:
            - StripPrefix=2

        - id: order-service-docs
          uri: lb://order-service
          predicates:
            - Path=/gateway/orders/v3/api-docs
          filters:
            - StripPrefix=2

        - id: admin-service-docs
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/v3/api-docs
          filters:
            - StripPrefix=2

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/gateway/catalog/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/gateway/orders/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/gateway/admin/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: auth-service
        url: /gateway/auth/v3/api-docs
      - name: catalog-service
        url: /gateway/catalog/v3/api-docs
      - name: order-service
        url: /gateway/orders/v3/api-docs
      - name: admin-service
        url: /gateway/admin/v3/api-docs
  api-docs:
    enabled: true
  use-management-port: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans


