server:
  port: 8085

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: yellendhar225@gmail.com
    password: ouycxexqrqbgztiq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
